Blog app - integration specs for views and fix n+1 problems
ZabihullahNooriWardak/BlogApp pull request #8
Opened 2023-12-13 18:20 UTC by ZabihullahNooriWardak

result before solving the n+1 problem : 
![285304100-ca7ff061-85c9-4cef-8df9-bca2ce22bd46](https://github.com/ZabihullahNooriWardak/BlogApp/assets/115200857/e2c8e589-4188-4ca4-b4b2-4fe9586da50e)
result after N+1 problem : 
![285304171-e9714ae6-71bd-4f64-9093-e117019d904e](https://github.com/ZabihullahNooriWardak/BlogApp/assets/115200857/731d69f0-94b5-45ed-a12f-44782cc86f60)

I have created integration tests using Capybara to thoroughly test each view in our project. The tests are organized to ensure a logical flow and cover various aspects of the user interface.
### User Index Page:
Verifies the visibility of usernames, profile pictures, and the number of posts for each user.
Validates the redirection to a user's show page upon clicking a user.
### User Show Page:

1. Ensures the display of the user's profile picture, username, bio, and the first three posts.
2. Includes a button to view all of a user's posts and verifies the redirection to a user's post index page upon clicking a user's post.
### User Post Index Page:
1. Validates the visibility of the user's profile picture, username, post details, comments, likes, and pagination functionality.
2. Verifies the redirection to a post's show page upon clicking a post.
### Post Show Page:
1. Ensures the visibility of the post's title, author, comments, likes, body, and the details of each comment.
2. These tests provide comprehensive coverage of our application's views and user interactions. Your feedback on this pull request is highly appreciated.

2023-12-13 20:54 UTC, Shedrack-Sunday requested changes
Hello @ZabihullahNooriWardak     👋 

# CHANGES REQUIRED ♻️

Impressive work on the project so far👏
You've done extremely well so far in this project,  However, there are some adjustments you need to make to move to the next project. 💯

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights   
- Good use of GitHub features ✔️   
- Nice work with Rails testing  features ✔️
- Great work on the  N+1  implementation to fix queries👏   



# - Required Changes  🌵  

- [ ] Kindly note  the comment i made regarding the issues on the error which stems from running your migrations, and a few test cases you missed
# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing really improves your application.



Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-12-13 20:54 UTC, Shedrack-Sunday commented on spec/integrations/users_show_spec.rb
> +
- [ ] You happen to miss a couple of tests needed for this file. 
- I can see the user's username.
 - I can see the number of posts the user has written.
 - When I click to see all posts, it redirects me to the user's post's index page.
 
 - [ ] Kindly add them up 👏 
 
 ### View 👍 
 
![image](https://github.com/ZabihullahNooriWardak/BlogApp/assets/50990925/7fa6b14a-426b-449f-8a50-5f3922e84685)

2023-12-13 20:54 UTC, Shedrack-Sunday commented on spec/integrations/posts_index_spec.rb
> +    visit path
- [ ] Kindly add the test `I can see the first comments on a post.`. This particular test is missing 

### View:
![image](https://github.com/ZabihullahNooriWardak/BlogApp/assets/50990925/c55c2ae9-f7ef-4eb2-bb94-17fb237adc65)

2023-12-13 20:54 UTC, Shedrack-Sunday commented on spec/integrations/posts_show_spec.rb
> +end
- [ ] Kindly complete the last test, `I can see the comment each comment left.`. Good job 👍 

### View:
![image](https://github.com/ZabihullahNooriWardak/BlogApp/assets/50990925/e80a5fad-e045-4cf0-8a77-45307b4a7b17)

2023-12-13 20:54 UTC, Shedrack-Sunday commented on db/migrate/20231026201955_add_index_to_posts.rb
> +end
- [ ] I had issues running this migration due to duplication of the id being passed already in a migration before this. kindly fix this error 👍 

### View:
 
![image](https://github.com/ZabihullahNooriWardak/BlogApp/assets/50990925/573a753a-f710-4923-acfe-7a0f7230ab78)

2023-12-14 04:08 UTC, zieeco requested changes
Hi @Team,

<img height="80" src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>



Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the changes, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- Requested changes implemented ✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._




## Optional suggestions
_Check the comments under the review._

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-14 04:08 UTC, zieeco commented on spec/features/user_show_spec.rb
> +end
- Hey, great job addressing all the changes pointed out by the previous reviewer, however, while you implemented the changes, you made some changes to your file naming which made it tedious to understand the changes you've made. consistent is key to a good code review workflow to foster readability in your codebase. Here is what you've done


   - You renamed the `integrations` to `features` in your spec file, which made it take time for me to trace your changes
   - You also have renamed `spec/integrations/users_show_spec.rb` to `spec/features/user_show_spec.rb`, see the file structure in the image below
 
*spec*  
![image](https://github.com/ZabihullahNooriWardak/BlogApp/assets/59397159/5edb8fed-c3f4-43ed-afb2-6b8e7be75b40)

*listing the files and directories in your spec file*
![image](https://github.com/ZabihullahNooriWardak/BlogApp/assets/59397159/e4b8682d-ab96-4e68-8dab-afe387557363)

---
- Although you've fixed all the required changes, I can't further approve your PR due to the changes you've made to the files and naming. Please, kindly follow the correct file naming convention as in the case of 
 `spec/features/user_show_spec.rb` which is meant to be pluralized `spec/features/users_show_spec.rb`.


- **[OPTIONAL]** Also, if possible rename the `features` to `integrations` as it was before. :muscle: 

Then, you can submit for another review, which your project would be approved.

2023-12-14 08:23 UTC, TedLivist approved these changes
## STATUS: APPROVED ✔️ ✔️

Hi @ZabihullahNooriWardak and @mahammad-mostafa,

✔️ Well-written and passing tests

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-14 08:41 UTC, merged